server:
  port: 8083

spring:
  application:
    name: file-status-processor
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: user
      password: pass
      database: filestatus
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      groupId: file-status-processor-id