spring:
  application:
    name: file-status-processor

---

spring:
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
      fail-fast: true